# Generated by Django 6.0.5 on 2026-05-15 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batting_hand', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=20)),
                ('playing_level', models.CharField(max_length=50)),
                ('archetype', models.CharField(blank=True, max_length=50, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.academy')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('date_analyzed', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.IntegerField(default=0)),
                ('primary_weakness', models.TextField(blank=True, null=True)),
                ('primary_strength', models.TextField(blank=True, null=True)),
                ('thing_to_change', models.TextField(blank=True, null=True)),
                ('bonus_insight', models.TextField(blank=True, null=True)),
                ('balance_score', models.IntegerField(default=0)),
                ('power_score', models.IntegerField(default=0)),
                ('technique_score', models.IntegerField(default=0)),
                ('defence_score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.playerprofile')),
            ],
        ),
    ]
