# Generated by Django 6.0.5 on 2026-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playerprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='title',
            field=models.CharField(default='Practice Session', max_length=200),
        ),
    ]
