# Generated by Django 6.0.5 on 2026-07-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysissession_status_analysissession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='attribution_drivers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='confidence_variance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
