# Generated by Django 6.0.5 on 2026-07-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_analysissession_attribution_drivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
