import os
import unittest
from unittest import mock

from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from rest_framework.test import APIClient

from api.models import Academy, AnalysisSession, PlayerProfile

# Create your tests here.

# The trained model file is gitignored and not committed (it's a large
# binary artifact, regenerated by the training pipeline) -- a fresh clone or
# a CI environment that hasn't staged it separately won't have it on disk.
# Tests that need a real loaded model skip cleanly instead of erroring with
# an unhelpful FileNotFoundError that looks like a real regression.
#
# Path resolution itself comes from ml_service.resolve_model_path() rather
# than being recomputed here -- reimplementing it would be exactly the kind
# of duplication this milestone exists to eliminate.
from api.ml_service import resolve_model_path
_MODEL_PATH = resolve_model_path()
_MODEL_AVAILABLE = os.path.exists(_MODEL_PATH)


class MLServiceSingleSourceOfTruthTests(TestCase):
    """Milestone 1 (ML single-source-of-truth consolidation): ml_service.py
    used to define its own TemporalAttention class and its own copy of the
    feature schema, independently of dataset/model_layers.py and
    dataset/schema.py. These tests assert it now imports the exact same
    objects -- not a separately-defined lookalike -- so the two can no
    longer silently drift apart."""

    def test_imports_canonical_attention_layer(self):
        from api import ml_service
        from model_layers import TemporalAttention
        self.assertIs(ml_service.TemporalAttention, TemporalAttention)

    def test_imports_canonical_feature_schema(self):
        from api import ml_service
        import schema
        self.assertIs(ml_service.FEATURE_COLS, schema.EXPECTED_FEATURES)
        self.assertEqual(ml_service.SEQ_LEN, schema.SEQ_LEN)
        self.assertIs(ml_service.FEATURE_BASE_NAMES, schema.FEATURE_BASE_NAMES)

    @unittest.skipUnless(_MODEL_AVAILABLE, f"model file not present at {_MODEL_PATH} (gitignored, not committed)")
    def test_deterministic_forward_pass_is_unchanged(self):
        # The one thing this milestone must never change: the model's actual
        # computation. Runs the real loaded model (dropout disabled, so the
        # result is deterministic) against a fixed synthetic input and checks
        # it produces a stable, finite, correctly-shaped output. This doesn't
        # replace the manual before/after real-video comparison already run
        # during implementation (which showed an exact float32 match), but it
        # gives CI a standing regression check going forward.
        import numpy as np
        from api import ml_service

        extractor, _ = ml_service.get_models()
        rng = np.random.default_rng(42)
        x = rng.random((1, ml_service.SEQ_LEN, len(ml_service.FEATURE_COLS))).astype(np.float32)
        scores, _ = extractor(x, training=False)
        scores = scores.numpy()

        self.assertEqual(scores.shape, (1, 4))
        self.assertTrue(np.all(np.isfinite(scores)))
        self.assertTrue(np.all((scores >= 0.0) & (scores <= 1.0)))  # sigmoid output, pre-scaling


class AnalyzeStancePlayerScopingTests(TestCase):
    """Regression tests for audit H7: analyze_stance used to get_or_create a
    PlayerProfile with a CLIENT-SUPPLIED primary key. If that id already
    existed in another academy, the create raised IntegrityError (an
    unhandled 500); any unknown id silently created a 'Guest Player' row at
    whatever pk the client chose. The lookup is now (id, academy) get-or-404
    and never creates."""

    ANALYZE_URL = "/api/sessions/analyze_stance/"

    def setUp(self):
        self.api = APIClient()
        coach_a = User.objects.create_user("coach_a@example.com", password="test-pass-1")
        # Verified: this class tests player_id/academy scoping (audit H7),
        # not the ISSUE-007 verification gate -- CoachVerificationGateTests
        # below covers unverified coaches.
        self.academy_a = Academy.objects.create(user=coach_a, academy_name="Academy A", is_verified=True)
        coach_b = User.objects.create_user("coach_b@example.com", password="test-pass-2")
        self.academy_b = Academy.objects.create(user=coach_b, academy_name="Academy B")
        self.player_b = PlayerProfile.objects.create(
            academy=self.academy_b, name="B Player", batting_hand="Right", playing_level="club"
        )
        self.api.force_authenticate(user=coach_a)

    def _upload(self, player_id):
        data = {
            "video": SimpleUploadedFile("clip.mp4", b"fake-video-bytes", content_type="video/mp4"),
            "title": "Test Session",
        }
        if player_id is not None:
            data["player_id"] = player_id
        return self.api.post(self.ANALYZE_URL, data, format="multipart")

    def test_other_academys_player_id_is_404_not_500(self):
        # Pre-fix behavior: IntegrityError (duplicate pk) -> unhandled 500.
        response = self._upload(self.player_b.id)
        self.assertEqual(response.status_code, 404)
        self.assertEqual(PlayerProfile.objects.count(), 1)  # nothing auto-created

    def test_nonexistent_player_id_is_404_and_creates_nothing(self):
        # Pre-fix behavior: silently created 'Guest Player' at the client's pk.
        response = self._upload(999999)
        self.assertEqual(response.status_code, 404)
        self.assertFalse(PlayerProfile.objects.filter(id=999999).exists())

    def test_non_integer_player_id_is_404_not_500(self):
        response = self._upload("not-a-number")
        self.assertEqual(response.status_code, 404)

    def test_own_academy_player_proceeds_to_inference(self):
        player_a = PlayerProfile.objects.create(
            academy=self.academy_a, name="A Player", batting_hand="Right", playing_level="club"
        )
        fake_scores = {
            "balance_score": 70, "power_score": 65, "technique_score": 72, "defence_score": 60,
            "overall_score": 66,
            "primary_weakness": "Defence (60/100) is the area to work on.",
            "primary_strength": "Technique (72/100) is the strongest part of this stance.",
            "recommended_drill": "Head-still drill",
            "confidence_variance": {"balance": 1.0, "power": 1.0, "technique": 1.0, "defence": 1.0},
            "attribution_drivers": ["head tilt / eye level"],
            "is_fallback": False,
        }
        with mock.patch("api.views.run_advanced_inference", return_value=fake_scores):
            response = self._upload(player_a.id)
        self.assertEqual(response.status_code, 200)
        session = AnalysisSession.objects.get(id=response.data["session_id"])
        self.assertEqual(session.player_id, player_a.id)
        self.assertEqual(session.defence_score, 60)


class CoachVerificationGateTests(TestCase):
    """Regression tests for ISSUE-007 / FR-AUTH-003: signing up with
    role=COACH used to make an account immediately fully functional. A coach
    Academy row now starts with is_verified=False, and coach-only actions
    (dashboard, analyze_stance-for-a-player, score overrides) must reject an
    unverified coach with 403 until an admin flips the flag."""

    ANALYZE_URL = "/api/sessions/analyze_stance/"
    COACH_DASHBOARD_URL = "/api/coach/me/"

    def setUp(self):
        self.api = APIClient()
        self.coach_user = User.objects.create_user("new_coach@example.com", password="test-pass-4")
        self.academy = Academy.objects.create(user=self.coach_user, academy_name="New Academy")
        self.assertFalse(self.academy.is_verified)  # the default this gate depends on
        self.player = PlayerProfile.objects.create(
            academy=self.academy, name="Player", batting_hand="Right", playing_level="club"
        )
        self.api.force_authenticate(user=self.coach_user)

    def test_unverified_coach_blocked_from_dashboard(self):
        response = self.api.get(self.COACH_DASHBOARD_URL)
        self.assertEqual(response.status_code, 403)

    def test_unverified_coach_blocked_from_analyze_stance(self):
        upload = SimpleUploadedFile("clip.mp4", b"fake-video-bytes", content_type="video/mp4")
        response = self.api.post(
            self.ANALYZE_URL,
            {"video": upload, "title": "T", "player_id": self.player.id},
            format="multipart",
        )
        self.assertEqual(response.status_code, 403)

    def test_unverified_coach_blocked_from_score_override(self):
        session = AnalysisSession.objects.create(player=self.player, balance_score=50)
        response = self.api.patch(f"/api/sessions/{session.id}/", {"balance_score": 90}, format="json")
        self.assertEqual(response.status_code, 403)
        session.refresh_from_db()
        self.assertEqual(session.balance_score, 50)  # untouched

    def test_verified_coach_reaches_dashboard(self):
        self.academy.is_verified = True
        self.academy.save()
        response = self.api.get(self.COACH_DASHBOARD_URL)
        self.assertEqual(response.status_code, 200)

    def test_registering_as_coach_starts_unverified(self):
        # End-to-end through RegisterView, not just direct model creation.
        api = APIClient()
        response = api.post(
            "/api/auth/register/",
            {"email": "brand_new_coach@example.com", "password": "test-pass-5",
             "name": "Brand New Academy", "role": "COACH"},
            format="json",
        )
        self.assertEqual(response.status_code, 201)
        self.assertEqual(response.data["user"]["is_verified"], False)
        academy = Academy.objects.get(user__email="brand_new_coach@example.com")
        self.assertFalse(academy.is_verified)


def _write_test_video(path, n_frames, fps=30.0, size=(64, 64)):
    """Writes a small black mp4 — enough to exercise the real decode path."""
    import cv2
    import numpy as np
    out = cv2.VideoWriter(path, cv2.VideoWriter_fourcc(*"mp4v"), fps, size)
    for _ in range(n_frames):
        out.write(np.zeros((size[1], size[0], 3), dtype=np.uint8))
    out.release()


def _fake_raw_keypoints(seq_len=7, n_landmarks=33):
    """Plausible extract_features_from_image_array output: values vary by
    frame and landmark so downstream angles/velocities are non-degenerate."""
    return [
        [[0.3 + 0.01 * f + 0.001 * j, 0.4 + 0.005 * f, 0.05 * j % 1.0, 1.0, 1.0]
         for j in range(n_landmarks)]
        for f in range(seq_len)
    ]


class UploadContractTests(TestCase):
    """Milestone 3 (audit C2, Option B upload contract): the serving path
    samples frames uniformly across the WHOLE clip, so the clip itself must
    be one pre-trimmed shot. Invalid uploads get a 400 with an actionable
    message — not a 500, and never a confidently-scored garbage result."""

    ANALYZE_URL = "/api/sessions/analyze_stance/"

    def setUp(self):
        import tempfile
        self.api = APIClient()
        learner = User.objects.create_user("learner@example.com", password="test-pass-3")
        self.player = PlayerProfile.objects.create(
            user=learner, name="Learner", batting_hand="Right", playing_level="club"
        )
        self.api.force_authenticate(user=learner)
        self._tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmpdir.cleanup)

    def _upload_video(self, n_frames=None, raw_bytes=None, fps=30.0):
        if raw_bytes is None:
            path = os.path.join(self._tmpdir.name, "clip.mp4")
            _write_test_video(path, n_frames, fps=fps)
            with open(path, "rb") as f:
                raw_bytes = f.read()
        upload = SimpleUploadedFile("clip.mp4", raw_bytes, content_type="video/mp4")
        return self.api.post(self.ANALYZE_URL, {"video": upload, "title": "T"}, format="multipart")

    def test_unreadable_file_is_rejected_400(self):
        response = self._upload_video(raw_bytes=b"this is not a video file")
        self.assertEqual(response.status_code, 400)
        self.assertIn("read", response.data["error"].lower())

    def test_overlong_clip_is_rejected_400_with_trim_guidance(self):
        # 21s at 30fps — over the 20s single-shot contract.
        response = self._upload_video(n_frames=630)
        self.assertEqual(response.status_code, 400)
        self.assertIn("trim", response.data["error"].lower())
        self.assertIn("20", response.data["error"])

    def test_too_short_clip_is_rejected_400(self):
        response = self._upload_video(n_frames=3)
        self.assertEqual(response.status_code, 400)
        self.assertIn("too short", response.data["error"].lower())

    def test_clip_with_no_detectable_pose_is_rejected_400(self):
        # 2s of black frames: passes the duration contract, then the REAL
        # pipeline validation (MediaPipe finds no pose, the interpolation
        # rules hard-reject) turns it into a clean 400 — previously this
        # produced either a 500 or a copied-frame garbage score.
        response = self._upload_video(n_frames=60)
        self.assertEqual(response.status_code, 400)
        self.assertIn("track", response.data["error"].lower())

    def test_ml_failure_falls_back_to_rule_based_scoring(self):
        # FR-ERR-001 preserved through the Milestone 3 rework: pose
        # extraction succeeds (mocked), the ML stage blows up, and the user
        # still gets a scored session flagged is_fallback — built from the
        # SAME keypoints via _keypoints_to_dataframe.
        with mock.patch("api.ml_service.extract_features_from_image_array",
                        return_value=(True, _fake_raw_keypoints(), [])), \
             mock.patch("api.ml_service._run_model_inference",
                        side_effect=RuntimeError("model exploded (test)")):
            response = self._upload_video(n_frames=30)
        self.assertEqual(response.status_code, 200)
        session = AnalysisSession.objects.get(id=response.data["session_id"])
        self.assertTrue(session.is_fallback)
        self.assertGreater(session.balance_score, 0)

    @unittest.skipUnless(_MODEL_AVAILABLE, f"model file not present at {_MODEL_PATH} (gitignored, not committed)")
    def test_valid_single_shot_clip_scores_via_real_model(self):
        # End-to-end through the view with only the pose detection mocked
        # (no human in a synthetic video): real tensor construction, real
        # MC-Dropout inference, real attribution, real persistence.
        with mock.patch("api.ml_service.extract_features_from_image_array",
                        return_value=(True, _fake_raw_keypoints(), [])):
            response = self._upload_video(n_frames=30)
        self.assertEqual(response.status_code, 200)
        session = AnalysisSession.objects.get(id=response.data["session_id"])
        self.assertFalse(session.is_fallback)
        for score in (session.balance_score, session.power_score,
                      session.technique_score, session.defence_score):
            self.assertGreaterEqual(score, 0)
            self.assertLessEqual(score, 100)
        self.assertIsNotNone(session.confidence_variance)


class TrainServeConsistencyTests(TestCase):
    """Milestone 3 (audit C2/M3): the guarantees are identity and numeric
    equivalence, not lookalike code — the same assertIs pattern Milestone 1
    established for the attention layer and feature schema."""

    def test_serving_reuses_the_exact_pipeline_functions(self):
        # Same function OBJECTS as dataset ingestion — validation and
        # interpolation cannot drift because they are not copies.
        import zero_storage_pipeline
        from api import ml_service
        self.assertIs(ml_service.extract_features_from_image_array,
                      zero_storage_pipeline.extract_features_from_image_array)
        self.assertIs(ml_service.collect_phase_frames,
                      zero_storage_pipeline.collect_phase_frames)

    def test_angle_math_matches_training_implementation(self):
        # The angle block in _run_model_inference is still a local copy
        # (consolidation is Milestone 7) — until then, prove numerically that
        # it matches the training-side implementation exactly.
        import numpy as np
        import pandas as pd
        from academic_scripts import feature_engineering
        from api import ml_service

        rng = np.random.default_rng(7)
        cols = {}
        for name in ("left_hip", "left_knee", "left_ankle", "right_shoulder", "nose"):
            for axis in ("x", "y", "z"):
                cols[f"{name}_{axis}"] = rng.random(7)
        df = pd.DataFrame(cols)

        np.testing.assert_allclose(
            ml_service.calculate_angle(df, "left_hip", "left_knee", "left_ankle"),
            feature_engineering.calculate_angle(df, "left_hip", "left_knee", "left_ankle"),
            rtol=0, atol=0,
        )
        np.testing.assert_allclose(
            ml_service.calculate_angle_with_vertical(df, "right_shoulder", "nose"),
            feature_engineering.calculate_angle_with_vertical(df, "right_shoulder", "nose"),
            rtol=0, atol=0,
        )

    def test_keypoints_to_dataframe_preserves_values_and_order(self):
        from api.ml_service import _keypoints_to_dataframe, landmarks_names
        raw = _fake_raw_keypoints()
        df = _keypoints_to_dataframe(raw)
        self.assertEqual(len(df), 7)
        self.assertEqual(len(df.columns), 33 * 3)  # x/y/z only, no visibility
        # Spot-check: frame 2, landmark 5 ("right_eye"), y coordinate.
        name = landmarks_names[5]
        self.assertEqual(df.loc[2, f"{name}_y"], raw[2][5][1])
        self.assertNotIn(f"{name}_v", df.columns)


class PerformanceEquivalenceTests(TestCase):
    """Milestone 5: the batched MC-Dropout / Expected-Gradients math and the
    locked model loading must be behaviorally equivalent to the sequential
    originals — proven, not assumed."""

    @unittest.skipUnless(_MODEL_AVAILABLE, f"model file not present at {_MODEL_PATH} (gitignored, not committed)")
    def test_get_models_is_threadsafe_and_loads_once(self):
        import threading
        import tensorflow as tf
        from api import ml_service

        # Force a fresh load so the test observes construction, then count
        # real load_model invocations across 6 racing threads.
        ml_service._extractor = None
        ml_service._att_layer = None
        real_load = tf.keras.models.load_model
        load_calls = []

        def counting_load(*args, **kwargs):
            load_calls.append(1)
            return real_load(*args, **kwargs)

        results = []
        with mock.patch.object(tf.keras.models, "load_model", side_effect=counting_load):
            threads = [threading.Thread(target=lambda: results.append(ml_service.get_models()))
                       for _ in range(6)]
            for t in threads:
                t.start()
            for t in threads:
                t.join()

        self.assertEqual(len(load_calls), 1)  # exactly one real model load
        first_extractor = results[0][0]
        for extractor, _ in results:
            self.assertIs(extractor, first_extractor)  # every thread got the same object

    @unittest.skipUnless(_MODEL_AVAILABLE, f"model file not present at {_MODEL_PATH} (gitignored, not committed)")
    def test_tiled_batch_is_rowwise_identical_to_single_pass_when_deterministic(self):
        # The core equivalence claim behind batched MC-Dropout, tested with
        # dropout DISABLED so the comparison is deterministic: a batch of 30
        # identical rows must produce 30 outputs identical to the single-row
        # output (proves tiling + BatchNorm introduce no cross-row coupling).
        import numpy as np
        from api import ml_service

        extractor, _ = ml_service.get_models()
        rng = np.random.default_rng(11)
        x = rng.random((1, ml_service.SEQ_LEN, len(ml_service.FEATURE_COLS))).astype(np.float32)

        single, _ = extractor(x, training=False)
        tiled, _ = extractor(np.repeat(x, ml_service.MC_DROPOUT_PASSES, axis=0), training=False)
        single, tiled = single.numpy(), tiled.numpy()

        for row in range(ml_service.MC_DROPOUT_PASSES):
            np.testing.assert_allclose(tiled[row], single[0], rtol=0, atol=1e-6)

    @unittest.skipUnless(_MODEL_AVAILABLE, f"model file not present at {_MODEL_PATH} (gitignored, not committed)")
    def test_batched_mc_dropout_statistics_match_sequential(self):
        # With dropout ON both estimators are stochastic; they must agree
        # within sampling noise. 0.05 on the 0-1 sigmoid scale is >6 standard
        # errors for this model's observed dropout spread — loose enough to
        # never flake, tight enough to catch a broken estimator.
        import numpy as np
        from api import ml_service

        extractor, _ = ml_service.get_models()
        rng = np.random.default_rng(12)
        x = rng.random((1, ml_service.SEQ_LEN, len(ml_service.FEATURE_COLS))).astype(np.float32)

        sequential = np.vstack([extractor(x, training=True)[0].numpy()
                                for _ in range(ml_service.MC_DROPOUT_PASSES)])
        batched = extractor(np.repeat(x, ml_service.MC_DROPOUT_PASSES, axis=0),
                            training=True)[0].numpy()

        self.assertEqual(batched.shape, sequential.shape)
        np.testing.assert_allclose(batched.mean(axis=0), sequential.mean(axis=0), atol=0.05)

    @unittest.skipUnless(_MODEL_AVAILABLE, f"model file not present at {_MODEL_PATH} (gitignored, not committed)")
    def test_batched_expected_gradients_matches_sequential_reference(self):
        # The batched implementation must reproduce the original sequential
        # algorithm (kept here as the reference) up to float reduction order,
        # including the top-2 driver ranking the product surfaces.
        import numpy as np
        import tensorflow as tf
        from api import ml_service

        extractor, _ = ml_service.get_models()
        rng = np.random.default_rng(13)
        x = rng.random((1, ml_service.SEQ_LEN, len(ml_service.FEATURE_COLS))).astype(np.float32)

        def sequential_reference(output_index, n_baselines=12, n_steps=6):
            backgrounds = ml_service._load_background_sequences(n_baselines)
            x_t = tf.constant(x, dtype=tf.float32)
            total = np.zeros(x.shape[1:], dtype=np.float32)
            for baseline in backgrounds:
                baseline_t = tf.constant(baseline[None, ...], dtype=tf.float32)
                diff = x_t - baseline_t
                grad_sum = tf.zeros_like(x_t)
                for step in range(1, n_steps + 1):
                    interpolated = baseline_t + (step / n_steps) * diff
                    with tf.GradientTape() as tape:
                        tape.watch(interpolated)
                        scores, _ = extractor(interpolated, training=False)
                        target = scores[:, output_index]
                    grad_sum += tape.gradient(target, interpolated)
                total += ((grad_sum / n_steps) * diff).numpy()[0]
            return total / len(backgrounds)

        for output_index in (0, 3):
            batched = ml_service._expected_gradients(extractor, x, output_index)
            reference = sequential_reference(output_index)
            np.testing.assert_allclose(batched, reference, rtol=1e-3, atol=1e-5)
            # Ranking the product actually surfaces must be identical.
            batched_rank = np.argsort(-np.sum(np.abs(batched), axis=0))[:2].tolist()
            reference_rank = np.argsort(-np.sum(np.abs(reference), axis=0))[:2].tolist()
            self.assertEqual(batched_rank, reference_rank)
